### ISSUE TITLE
work with react-router-redux

### ISSUE THREAD

**Issue by leecade** [jaystack/repatch#4]
Try out for a few days, it's an awesome redux alternative solution, I'd like to migrate from redux, and request a demo or snippet how to work with router here, thx

ref: https://github.com/ReactTraining/react-router/tree/master/packages/react-router-redux

**Comment by jayhasyee** [comment]
@leecade `react-router-redux` cannot work directly with `repatch`, because `repatch` does not handle `redux`'s action objects.
But.
I can offer a way to migrate your project while we are considering a `react-router-repatch` package.
First you should create a simple middleware to handle history methods:

```javascript
import { CALL_HISTORY_METHOD, LOCATION_CHANGE } from 'react-router-redux';

const routerMiddleware = history => (store, reducer) => {
  if (typeof reducer !== 'object') return reducer;
  if (reducer.type === CALL_HISTORY_METHOD) {
    const { payload: { method, args } } = reducer;
    history[method](...args);
    return reducer; // you can return it safely, because repatch won't handle a non-function reducer
  }
  else if (reducer.type === LOCATION_CHANGE) {
    const { payload: location } = reducer;
    return state => ({ ...state, location });
  }
}
```

Then you can use the `ConnectedRouter` and actions of `react-router-redux`, after you add this middleware to the store:

```javascript
import createHistory from 'history/createBrowserHistory';
import { ConnectedRouter } from 'react-router-redux';

const history = createHistory();

const store = new Store({ ...yourInitialState, location: null })
  .addMiddleware(routerMiddleware(history))

ReactDOM.render(
  <Provider store={store}>
    { /* ConnectedRouter will use the store from Provider automatically */ }
    <ConnectedRouter history={history}>
      <div>
        <Route exact path="/" component={Home}/>
        <Route path="/about" component={About}/>
        <Route path="/topics" component={Topics}/>
      </div>
    </ConnectedRouter>
  </Provider>,
  document.getElementById('root')
)
```

I didn't try it, but I guess this will work. It is just a draft. Sorry if it contains mistakes.
But I am happy that you choose `repatch` :)
Thank you for your proposal!

**Comment by leecade** [comment]
yip, thanks for your tips, I'll try it by myself.

**Comment by jayhasyee** [comment]
@leecade please notify me, if it works well. Thanks!

**Comment by leecade** [comment]
Seems there is a conflict definition about `reducer`.

`repatch` assume that the `reducer` can only be function.

ref: https://github.com/jaystack/repatch/blob/master/src/store/index.ts#L48

but for work with `react-router-redux`, the `reducer` should be object.

ref: https://github.com/ReactTraining/react-router/blob/master/packages/react-router-redux/modules/actions.js#L9

ref: https://github.com/ReactTraining/react-router/blob/master/packages/react-router-redux/modules/ConnectedRouter.js#L19

```js
const routerMiddleware = history => (store, reducer) => {
  // here
  if (typeof reducer === 'object' && reducer.type === CALL_HISTORY_METHOD) {
```

**Comment by jayhasyee** [comment]
Indeed. However I think this assertion is not necessary, because this is allowed that middlewares can transform the reducer, even its types too. For example `thunk` do this.
A key-moment via dispatching is deciding to run or not a reducer:
https://github.com/jaystack/repatch/blob/master/src/store/index.ts#L24
So, I don't think this assertion is required. I have to consider to remove that.

**Comment by leecade** [comment]
Hope won't affect other features, I will come back once finished.

**Comment by jayhasyee** [comment]
@leecade I didn't remove the assertion.
Instead of that I updated the middleware signature and mechanism.
Now middlewares are very similar to redux:
```
Middleware: Store -> Next -> Reducer -> any
```
And the significant change is, that middlewares now enhacne the store instance instead of moving them into the store. Therefore the original `dispatch` won't get your objects as reducers, because before it runs, your middleware will be invoked. You can imagine that the middlewares wrap the store instance with a new `dispatch` method.

These changes came with the `1.1.0` minor version.

I updated your middleware for this:

```javascript
const routerMiddleware = history => store => next => reducer => {
  if (typeof reducer === 'object' && reducer.type === CALL_HISTORY_METHOD) {
    const { payload: { method, args } } = reducer;
    history[method](...args);
    return reducer;
  } else if (typeof reducer === 'object' && reducer.type === LOCATION_CHANGE) {
    const { payload: location } = reducer;
    return next(state => ({ ...state, router: { ...state.router, location } }));
  }
  return next(reducer);
};
```

I tried it without the `react-router-redux`, and I found that works properly. Now the `dispatch` won't throw assertion error. If you use `thunk` middleware you have to add `routerMiddleware` at last, because then that will be invoked first.

I am glad for your issue. This issue revealed a design problem in repatch and I could fix that before it comes too late.

**Comment by leecade** [comment]
In my case, `react-router-redux` works well with `1.1.0`, just notify you that.

When I free I'd glad to create a `react-router-redux` + `repatch` demo.

Great job, Thanks again.
